# Site settings
title: Nat & Drew are getting married! <3
email: iamdrew@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: ""
url: "https://drewn.at" # the base hostname & protocol for your site

twitter_username: rewcore
github_username: hybby

# Build settings
markdown: kramdown
